/**
 * Get a deterministic quote based on current date.
 * Same quote is returned throughout the entire day.
 */
export function getDailyQuote() {
  const today = new Date();
  // Create a seed from the date (YYYYMMDD format as number)
  const seed = today.getFullYear() * 10000 + (today.getMonth() + 1) * 100 + today.getDate();
  // Use modulo to get a consistent index for this day
  const index = seed % welcomeQuotes.length;
  return welcomeQuotes[index];
}

export const welcomeQuotes: { quote: string; author: string }[] = [
  { quote: "We do not remember days; we remember moments.", author: "Cesare Pavese" },
  { quote: "Memory is the diary that we all carry about with us.", author: "Oscar Wilde" },
  { quote: "What we once enjoyed we can never lose.", author: "Helen Keller" },
  { quote: "The life of the dead is placed in the memory of the living.", author: "Marcus Tullius Cicero" },
  { quote: "Nothing is ever really lost to us as long as we remember it.", author: "L.M. Montgomery" },
  { quote: "We never know when we are making a memory.", author: "Rickie Lee Jones" },
  { quote: "Time moves in one direction, memory in another.", author: "William Gibson" },
  { quote: "Memory is the key not to the past, but to the future.", author: "Corrie Ten Boom" },
  { quote: "A picture is a secret about a secret, the more it tells you the less you know.", author: "Diane Arbus" },
  { quote: "Sometimes you will never know the value of a moment until it becomes a memory.", author: "Dr. Seuss" },

  { quote: "Memory is the only paradise from which we cannot be driven.", author: "Jean Paul" },
  { quote: "Memory is how we keep telling ourselves our stories.", author: "Alice Munro" },
  { quote: "Take care of all your memories, for you cannot relive them.", author: "Bob Dylan" },
  { quote: "Photography takes an instant out of time, altering life by holding it still.", author: "Dorothea Lange" },
  { quote: "We are cups, constantly and quietly being filled. The trick is knowing how to tip ourselves over and let the beautiful stuff out.", author: "Ray Bradbury" },
  { quote: "A life is made in moments of great meaning.", author: "Annie Dillard" },
  { quote: "God gave us memory so that we might have roses in December.", author: "J.M. Barrie" },
  { quote: "What is remembered, lives.", author: "Lao Tzu" },
  { quote: "Remembrance of things past is not necessarily the remembrance of things as they were.", author: "Marcel Proust" },
  { quote: "A photograph is the pause button on life.", author: "Unknown" },

  { quote: "Memories warm you up from the inside. But they also tear you apart.", author: "Haruki Murakami" },
  { quote: "We are made of memories; first we remember, then we live.", author: "Oscar Wilde" },
  { quote: "The past is a guidepost, not a hitching post.", author: "L. Thomas Holdcroft" },
  { quote: "Memory is the treasury and guardian of all things.", author: "Marcus Tullius Cicero" },
  { quote: "A photograph records the spectrum of light. A memory records the spectrum of feeling.", author: "Unknown" },
  { quote: "Memories are the key not to the past, but to the future.", author: "Corrie Ten Boom" },
  { quote: "The best thing about memories is making them.", author: "Unknown" },
  { quote: "Happiness is only real when shared.", author: "Christopher McCandless" },
  { quote: "We live for the moments we cannot put into words.", author: "Unknown" },
  { quote: "Sometimes the smallest things take up the most room in your heart.", author: "Winnie the Pooh (A.A. Milne)" },

  { quote: "The heart’s memory eliminates the bad and magnifies the good.", author: "Gustav Flaubert" },
  { quote: "What we have once enjoyed we can never lose; all that we love deeply becomes a part of us.", author: "Helen Keller" },
  { quote: "Memory is more indelible than ink.", author: "Eudora Welty" },
  { quote: "The camera is an instrument that teaches people how to see without a camera.", author: "Dorothea Lange" },
  { quote: "Do not count the days, make the days count.", author: "Muhammad Ali" },
  { quote: "Keep memories that make you smile.", author: "Unknown" },
  { quote: "The past beats inside me like a second heart.", author: "John Banville" },
  { quote: "Life can only be understood backwards; but it must be lived forwards.", author: "Søren Kierkegaard" },
  { quote: "Nothing fixes a thing so intensely in the memory as the wish to forget it.", author: "Michel de Montaigne" },
  { quote: "A photograph is a moral decision taken in one eighth of a second.", author: "Salman Rushdie" },

  { quote: "Photographs are a way of imprisoning reality, understood as receding past.", author: "Susan Sontag" },
  { quote: "I can shake off everything as I write; my sorrows disappear, my courage is reborn.", author: "Anne Frank" },
  { quote: "Memory is a complicated thing, a relative to truth but not its twin.", author: "Barbara Kingsolver" },
  { quote: "To be forgotten is worse than death.", author: "Publilius Syrus" },
  { quote: "The human heart is a storybook, and memory the ink.", author: "Unknown" },
  { quote: "We do not remember days, we remember moments.", author: "Cesare Pavese" },
  { quote: "A picture is a poem without words.", author: "Horace" },
  { quote: "The camera makes you forget you’re there. It’s not like you are hiding but you forget, you are just looking so much.", author: "Henri Cartier-Bresson" },
  { quote: "Some memories are realities, and are better than anything that can happen to one again.", author: "Willa Cather" },
  { quote: "The shortest word with the deepest meaning is 'remember.'", author: "Unknown" },

  { quote: "Memory is a map, not the territory.", author: "David Eagleman" },
  { quote: "The camera is an excuse to be someplace you otherwise don't belong.", author: "Susan Sontag" },
  { quote: "Memories are the stories we tell ourselves about ourselves.", author: "Homer" },
  { quote: "There are moments that define us. Keep them close.", author: "Unknown" },
  { quote: "Memories are like threads that stitch our life together.", author: "Unknown" },
  { quote: "The past is never dead. It’s not even past.", author: "William Faulkner" },
  { quote: "Memory is the presence of the past.", author: "Gustave Flaubert" },
  { quote: "A life without memories is like a book without pages.", author: "Unknown" },
  { quote: "To photograph is to hold one’s breath, when all faculties converge to capture an impression.", author: "Henri Cartier-Bresson" },
  { quote: "Your life is your story; write well.", author: "Unknown" },

  { quote: "Memory is the scribe of the soul.", author: "Lucy Larcom" },
  { quote: "The joy of being with those we love is life's greatest memory bank.", author: "Unknown" },
  { quote: "A photograph is a secret about a secret.", author: "Diane Arbus" },
  { quote: "What we record, we keep.", author: "Unknown" },
  { quote: "The past lives in our memories; guard them well.", author: "Unknown" },
  { quote: "We keep those we love in the chambers of memory.", author: "Unknown" },
  { quote: "A story is a way to hold on to what mattered.", author: "Unknown" },
  { quote: "The camera witnesses what the heart cannot always hold.", author: "Unknown" },
  { quote: "Remembrance is the only paradise from which we cannot be expelled.", author: "Jean Paul" },
  { quote: "Sometimes memories are the only souvenirs we have left.", author: "Unknown" },

  { quote: "Memory is the treasure house of the mind.", author: "Thomas Fuller" },
  { quote: "A picture is memory’s faithful courier.", author: "Unknown" },
  { quote: "The sound of a voice can bring someone back to you.", author: "Unknown" },
  { quote: "Not all memory is history; some is simply feeling.", author: "Unknown" },
  { quote: "Cherish what makes you smile today.", author: "Unknown" },
  { quote: "We gather moments like seashells on the shore of time.", author: "Unknown" },
  { quote: "What we save becomes who we are.", author: "Unknown" },
  { quote: "Stories are the vessels of lived experience.", author: "Unknown" },
  { quote: "Memory is the artist that paints our lives.", author: "Unknown" },
  { quote: "Pictures show where we have been; memories show who we were there with.", author: "Unknown" },

  { quote: "A good snapshot keeps a moment from running away.", author: "Eudora Welty" },
  { quote: "We write to taste life twice.", author: "Anaïs Nin" },
  { quote: "The past is a living thing that breathes in us.", author: "Unknown" },
  { quote: "Memories aren’t just stored. They’re curated.", author: "Unknown" },
  { quote: "The best souvenirs are the memories we keep.", author: "Unknown" },
  { quote: "Recording is an act of love.", author: "Unknown" },
  { quote: "Memory keeps the heart from being lonely.", author: "Unknown" },
  { quote: "Keep what matters. Let the rest go.", author: "Unknown" },
  { quote: "The camera captures; the heart keeps.", author: "Unknown" },
  { quote: "Memory is the antidote to loss.", author: "Unknown" },

  { quote: "A life remembered is a life honored.", author: "Unknown" },
  { quote: "We are all archivists of our own time.", author: "Unknown" },
  { quote: "A moment held is a story saved.", author: "Unknown" },
  { quote: "Memory: the only luxury that grows richer with use.", author: "Unknown" },
  { quote: "Photographs are the footprints of a life.", author: "Unknown" },
  { quote: "Write down the small things; they'll return bigger than you expect.", author: "Unknown" },
  { quote: "The memory holds the flame of what we loved.", author: "Unknown" },
  { quote: "What we remember sculpts our future.", author: "Unknown" },
  { quote: "To remember is to keep the door open.", author: "Unknown" },
  { quote: "Memory is the echo of living fully.", author: "Unknown" },

  { quote: "We are built from remembered kindnesses.", author: "Unknown" },
  { quote: "The camera freezes the world so memory can resume it later.", author: "Unknown" },
  { quote: "Some things are kept not for ourselves but for those who come after.", author: "Unknown" },
  { quote: "Memory threads generation to generation.", author: "Unknown" },
  { quote: "Every recorded laugh is a small victory against forgetting.", author: "Unknown" },
  { quote: "The smallest moment often holds a life’s meaning.", author: "Unknown" },
  { quote: "Memory is what remains when everything else has vanished.", author: "Unknown" },
  { quote: "A journal keeps your past close enough to learn from.", author: "Unknown" },
  { quote: "The photograph whispers the names of those who were there.", author: "Unknown" },
  { quote: "We save stories so the future can know our present.", author: "Unknown" },

  { quote: "Memory is home for what the heart cannot lose.", author: "Unknown" },
  { quote: "A recorded voice is presence preserved.", author: "Unknown" },
  { quote: "If memory is a museum, photographs are the plaques.", author: "Unknown" },
  { quote: "What you keep is what you teach others to value.", author: "Unknown" },
  { quote: "Memory is the soft architecture of identity.", author: "Unknown" },
  { quote: "Keep photographs; they are doorways for memory.", author: "Unknown" },
  { quote: "A saved story is a rebellion against oblivion.", author: "Unknown" },
  { quote: "The past visits us through what we have kept.", author: "Unknown" },
  { quote: "Memory is the compass of a life lived.", author: "Unknown" },
  { quote: "Capture the ordinary; it becomes extraordinary later.", author: "Unknown" },

  { quote: "Memory is the keeping place of love.", author: "Unknown" },
  { quote: "A day remembered is a day not wasted.", author: "Unknown" },
  { quote: "Photographs are time arrested for affection.", author: "Unknown" },
  { quote: "We hold people by remembering them.", author: "Unknown" },
  { quote: "Memories make a house into a home.", author: "Unknown" },
  { quote: "The past shapes us through what we choose to keep.", author: "Unknown" },
  { quote: "A memory well kept is a gift to the future.", author: "Unknown" },
  { quote: "Our lives are stitched from moments we saved.", author: "Unknown" },
  { quote: "Record what you love, and love will visit again.", author: "Unknown" },
  { quote: "Memory is the thread that sews our days together.", author: "Unknown" },

  { quote: "A good photograph is a small revolution of attention.", author: "Unknown" },
  { quote: "Memories forge identity over time.", author: "Unknown" },
  { quote: "The act of saving is an act of trust in tomorrow.", author: "Unknown" },
  { quote: "Sometimes remembering is the kindest thing we can do.", author: "Unknown" },
  { quote: "Preserve the faces that made you who you are.", author: "Unknown" },
  { quote: "Journals turn moments into counsel for the future.", author: "Unknown" },
  { quote: "Memory keeps the soul company when bodies part.", author: "Unknown" },
  { quote: "A photograph is a bridge to a moment otherwise lost.", author: "Unknown" },
  { quote: "The archive of life begins with a single saved memory.", author: "Unknown" },
  { quote: "Keep the little rituals; they become the big stories.", author: "Unknown" },

  { quote: "Memories survive where objects cannot.", author: "Unknown" },
  { quote: "Every recorded song is a future comfort.", author: "Unknown" },
  { quote: "We remember to remake ourselves wiser.", author: "Unknown" },
  { quote: "A saved note can be a lighthouse in dark times.", author: "Unknown" },
  { quote: "Memory is where we shelter what we treasure.", author: "Unknown" },
  { quote: "The best photograph is the one that brings you home.", author: "Unknown" },
  { quote: "Record the things that make you laugh.", author: "Unknown" },
  { quote: "Memories are heirlooms we carry inside us.", author: "Unknown" },
  { quote: "To forget is to lose a room from your inner house.", author: "Unknown" },
  { quote: "Keep provenance of love: names, dates, small details.", author: "Unknown" },

  { quote: "Memory is the soft map of our lived geography.", author: "Unknown" },
  { quote: "We preserve to ensure someone remembers with feeling.", author: "Unknown" },
  { quote: "A photograph is the soul’s shorthand.", author: "Unknown" },
  { quote: "Memories teach us how to be human.", author: "Unknown" },
  { quote: "To save a memory is to say 'you mattered.'", author: "Unknown" },
  { quote: "Recording memory is a tiny immortality.", author: "Unknown" },
  { quote: "Every saved moment is an argument against oblivion.", author: "Unknown" },
  { quote: "Memories are the quiet inheritance we leave.", author: "Unknown" },
  { quote: "Photographs are bookmarks in the library of life.", author: "Unknown" },
  { quote: "Hold on to the people who made you laugh.", author: "Unknown" },

  { quote: "Memory is not a container but a conversation.", author: "Unknown" },
  { quote: "What you preserve becomes the language of your family.", author: "Unknown" },
  { quote: "A voice recording brings someone back in a breath.", author: "Unknown" },
  { quote: "Our memories are the scaffolding of meaning.", author: "Unknown" },
  { quote: "Pictures are the face of private time.", author: "Unknown" },
  { quote: "Journals are maps for the interior life.", author: "Unknown" },
  { quote: "Keep mornings you never want to lose.", author: "Unknown" },
  { quote: "The most ordinary days often become treasured memories.", author: "Unknown" },
  { quote: "Memory is the quiet historian of the heart.", author: "Unknown" },
  { quote: "To catalogue a life is to love it more carefully.", author: "Unknown" },

  { quote: "Photographs are small monuments to what we felt.", author: "Unknown" },
  { quote: "Memory holds the names of the people who mattered.", author: "Unknown" },
  { quote: "A recorded laugh is an echo that never dies.", author: "Unknown" },
  { quote: "Keep the letters; they keep the voice alive.", author: "Unknown" },
  { quote: "Memory asks us to be witnesses to our own lives.", author: "Unknown" },
  { quote: "Memory is the tether that keeps us human.", author: "Unknown" },
  { quote: "Preserve the ordinary; it becomes extraordinary with time.", author: "Unknown" },
  { quote: "Photographs are proof that love once existed in a place.", author: "Unknown" },
  { quote: "Write the small details; they anchor the big feelings.", author: "Unknown" },
  { quote: "The archive of love is built from small gestures.", author: "Unknown" },

  { quote: "Memory sifts life into meaning.", author: "Unknown" },
  { quote: "A life recorded is a life that can be revisited.", author: "Unknown" },
  { quote: "What we capture invites future questions and kindness.", author: "Unknown" },
  { quote: "Keep the faces, keep the laughter, keep the names.", author: "Unknown" },
  { quote: "Memory is the quiet engine of gratitude.", author: "Unknown" },
  { quote: "Photographs are the grammar of memory.", author: "Unknown" },
  { quote: "Journaling is a conversation with the person you will be.", author: "Unknown" },
  { quote: "Memories make us portable across time.", author: "Unknown" },
  { quote: "Record now so the future remembers with tenderness.", author: "Unknown" },
  { quote: "A single note can call the past back to you.", author: "Unknown" },

  { quote: "Memory is the soft light that reveals what mattered.", author: "Unknown" },
  { quote: "Every day holds a moment worth saving.", author: "Unknown" },
  { quote: "Permanence is an act of careful remembering.", author: "Unknown" },
  { quote: "Photographs become the family’s visual language.", author: "Unknown" },
  { quote: "Keep diaries—the smallest observations become wisdom.", author: "Unknown" },
  { quote: "To cherish is to record.", author: "Unknown" },
  { quote: "Saving a moment is performing an act of love.", author: "Unknown" },
  { quote: "Memories are the soft scaffolding of our identity.", author: "Unknown" },
  { quote: "Where memory lives, love endures.", author: "Unknown" },
  { quote: "A photograph is a kindness to the future.", author: "Unknown" }
];