/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultsRouteImport } from './routes/vaults'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as PairingRouteImport } from './routes/pairing'
import { Route as MapRouteImport } from './routes/map'
import { Route as ImportRouteImport } from './routes/import'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GalleryIndexRouteImport } from './routes/gallery.index'
import { Route as QrExportVaultIdRouteImport } from './routes/qr-export.$vaultId'
import { Route as GalleryMemoriesIndexRouteImport } from './routes/gallery.memories.index'
import { Route as GalleryMemoriesIdRouteImport } from './routes/gallery.memories.$id'

const VaultsRoute = VaultsRouteImport.update({
  id: '/vaults',
  path: '/vaults',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const PairingRoute = PairingRouteImport.update({
  id: '/pairing',
  path: '/pairing',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GalleryRoute,
} as any)
const QrExportVaultIdRoute = QrExportVaultIdRouteImport.update({
  id: '/qr-export/$vaultId',
  path: '/qr-export/$vaultId',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryMemoriesIndexRoute = GalleryMemoriesIndexRouteImport.update({
  id: '/memories/',
  path: '/memories/',
  getParentRoute: () => GalleryRoute,
} as any)
const GalleryMemoriesIdRoute = GalleryMemoriesIdRouteImport.update({
  id: '/memories/$id',
  path: '/memories/$id',
  getParentRoute: () => GalleryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/import': typeof ImportRoute
  '/map': typeof MapRoute
  '/pairing': typeof PairingRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/setup': typeof SetupRoute
  '/vaults': typeof VaultsRoute
  '/qr-export/$vaultId': typeof QrExportVaultIdRoute
  '/gallery/': typeof GalleryIndexRoute
  '/gallery/memories/$id': typeof GalleryMemoriesIdRoute
  '/gallery/memories': typeof GalleryMemoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/map': typeof MapRoute
  '/pairing': typeof PairingRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/setup': typeof SetupRoute
  '/vaults': typeof VaultsRoute
  '/qr-export/$vaultId': typeof QrExportVaultIdRoute
  '/gallery': typeof GalleryIndexRoute
  '/gallery/memories/$id': typeof GalleryMemoriesIdRoute
  '/gallery/memories': typeof GalleryMemoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/import': typeof ImportRoute
  '/map': typeof MapRoute
  '/pairing': typeof PairingRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/setup': typeof SetupRoute
  '/vaults': typeof VaultsRoute
  '/qr-export/$vaultId': typeof QrExportVaultIdRoute
  '/gallery/': typeof GalleryIndexRoute
  '/gallery/memories/$id': typeof GalleryMemoriesIdRoute
  '/gallery/memories/': typeof GalleryMemoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gallery'
    | '/import'
    | '/map'
    | '/pairing'
    | '/scan'
    | '/search'
    | '/setup'
    | '/vaults'
    | '/qr-export/$vaultId'
    | '/gallery/'
    | '/gallery/memories/$id'
    | '/gallery/memories'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/import'
    | '/map'
    | '/pairing'
    | '/scan'
    | '/search'
    | '/setup'
    | '/vaults'
    | '/qr-export/$vaultId'
    | '/gallery'
    | '/gallery/memories/$id'
    | '/gallery/memories'
  id:
    | '__root__'
    | '/'
    | '/gallery'
    | '/import'
    | '/map'
    | '/pairing'
    | '/scan'
    | '/search'
    | '/setup'
    | '/vaults'
    | '/qr-export/$vaultId'
    | '/gallery/'
    | '/gallery/memories/$id'
    | '/gallery/memories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalleryRoute: typeof GalleryRouteWithChildren
  ImportRoute: typeof ImportRoute
  MapRoute: typeof MapRoute
  PairingRoute: typeof PairingRoute
  ScanRoute: typeof ScanRoute
  SearchRoute: typeof SearchRoute
  SetupRoute: typeof SetupRoute
  VaultsRoute: typeof VaultsRoute
  QrExportVaultIdRoute: typeof QrExportVaultIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vaults': {
      id: '/vaults'
      path: '/vaults'
      fullPath: '/vaults'
      preLoaderRoute: typeof VaultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pairing': {
      id: '/pairing'
      path: '/pairing'
      fullPath: '/pairing'
      preLoaderRoute: typeof PairingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/qr-export/$vaultId': {
      id: '/qr-export/$vaultId'
      path: '/qr-export/$vaultId'
      fullPath: '/qr-export/$vaultId'
      preLoaderRoute: typeof QrExportVaultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/memories/': {
      id: '/gallery/memories/'
      path: '/memories'
      fullPath: '/gallery/memories'
      preLoaderRoute: typeof GalleryMemoriesIndexRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/gallery/memories/$id': {
      id: '/gallery/memories/$id'
      path: '/memories/$id'
      fullPath: '/gallery/memories/$id'
      preLoaderRoute: typeof GalleryMemoriesIdRouteImport
      parentRoute: typeof GalleryRoute
    }
  }
}

interface GalleryRouteChildren {
  GalleryIndexRoute: typeof GalleryIndexRoute
  GalleryMemoriesIdRoute: typeof GalleryMemoriesIdRoute
  GalleryMemoriesIndexRoute: typeof GalleryMemoriesIndexRoute
}

const GalleryRouteChildren: GalleryRouteChildren = {
  GalleryIndexRoute: GalleryIndexRoute,
  GalleryMemoriesIdRoute: GalleryMemoriesIdRoute,
  GalleryMemoriesIndexRoute: GalleryMemoriesIndexRoute,
}

const GalleryRouteWithChildren =
  GalleryRoute._addFileChildren(GalleryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalleryRoute: GalleryRouteWithChildren,
  ImportRoute: ImportRoute,
  MapRoute: MapRoute,
  PairingRoute: PairingRoute,
  ScanRoute: ScanRoute,
  SearchRoute: SearchRoute,
  SetupRoute: SetupRoute,
  VaultsRoute: VaultsRoute,
  QrExportVaultIdRoute: QrExportVaultIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
