/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GalleryIndexRouteImport } from './routes/gallery.index'
import { Route as GalleryMemoriesIndexRouteImport } from './routes/gallery.memories.index'
import { Route as GalleryMemoriesIdRouteImport } from './routes/gallery.memories.$id'

const VaultsLazyRouteImport = createFileRoute('/vaults')()
const SetupLazyRouteImport = createFileRoute('/setup')()
const ScanLazyRouteImport = createFileRoute('/scan')()
const PairingLazyRouteImport = createFileRoute('/pairing')()
const ImportLazyRouteImport = createFileRoute('/import')()
const IndexLazyRouteImport = createFileRoute('/')()

const VaultsLazyRoute = VaultsLazyRouteImport.update({
  id: '/vaults',
  path: '/vaults',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/vaults.lazy').then((d) => d.Route))
const SetupLazyRoute = SetupLazyRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/setup.lazy').then((d) => d.Route))
const ScanLazyRoute = ScanLazyRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/scan.lazy').then((d) => d.Route))
const PairingLazyRoute = PairingLazyRouteImport.update({
  id: '/pairing',
  path: '/pairing',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/pairing.lazy').then((d) => d.Route))
const ImportLazyRoute = ImportLazyRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/import.lazy').then((d) => d.Route))
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GalleryRoute,
} as any)
const GalleryMemoriesIndexRoute = GalleryMemoriesIndexRouteImport.update({
  id: '/memories/',
  path: '/memories/',
  getParentRoute: () => GalleryRoute,
} as any)
const GalleryMemoriesIdRoute = GalleryMemoriesIdRouteImport.update({
  id: '/memories/$id',
  path: '/memories/$id',
  getParentRoute: () => GalleryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/import': typeof ImportLazyRoute
  '/pairing': typeof PairingLazyRoute
  '/scan': typeof ScanLazyRoute
  '/setup': typeof SetupLazyRoute
  '/vaults': typeof VaultsLazyRoute
  '/gallery/': typeof GalleryIndexRoute
  '/gallery/memories/$id': typeof GalleryMemoriesIdRoute
  '/gallery/memories': typeof GalleryMemoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/import': typeof ImportLazyRoute
  '/pairing': typeof PairingLazyRoute
  '/scan': typeof ScanLazyRoute
  '/setup': typeof SetupLazyRoute
  '/vaults': typeof VaultsLazyRoute
  '/gallery': typeof GalleryIndexRoute
  '/gallery/memories/$id': typeof GalleryMemoriesIdRoute
  '/gallery/memories': typeof GalleryMemoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/import': typeof ImportLazyRoute
  '/pairing': typeof PairingLazyRoute
  '/scan': typeof ScanLazyRoute
  '/setup': typeof SetupLazyRoute
  '/vaults': typeof VaultsLazyRoute
  '/gallery/': typeof GalleryIndexRoute
  '/gallery/memories/$id': typeof GalleryMemoriesIdRoute
  '/gallery/memories/': typeof GalleryMemoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gallery'
    | '/import'
    | '/pairing'
    | '/scan'
    | '/setup'
    | '/vaults'
    | '/gallery/'
    | '/gallery/memories/$id'
    | '/gallery/memories'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/import'
    | '/pairing'
    | '/scan'
    | '/setup'
    | '/vaults'
    | '/gallery'
    | '/gallery/memories/$id'
    | '/gallery/memories'
  id:
    | '__root__'
    | '/'
    | '/gallery'
    | '/import'
    | '/pairing'
    | '/scan'
    | '/setup'
    | '/vaults'
    | '/gallery/'
    | '/gallery/memories/$id'
    | '/gallery/memories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  GalleryRoute: typeof GalleryRouteWithChildren
  ImportLazyRoute: typeof ImportLazyRoute
  PairingLazyRoute: typeof PairingLazyRoute
  ScanLazyRoute: typeof ScanLazyRoute
  SetupLazyRoute: typeof SetupLazyRoute
  VaultsLazyRoute: typeof VaultsLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vaults': {
      id: '/vaults'
      path: '/vaults'
      fullPath: '/vaults'
      preLoaderRoute: typeof VaultsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pairing': {
      id: '/pairing'
      path: '/pairing'
      fullPath: '/pairing'
      preLoaderRoute: typeof PairingLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/gallery/memories/': {
      id: '/gallery/memories/'
      path: '/memories'
      fullPath: '/gallery/memories'
      preLoaderRoute: typeof GalleryMemoriesIndexRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/gallery/memories/$id': {
      id: '/gallery/memories/$id'
      path: '/memories/$id'
      fullPath: '/gallery/memories/$id'
      preLoaderRoute: typeof GalleryMemoriesIdRouteImport
      parentRoute: typeof GalleryRoute
    }
  }
}

interface GalleryRouteChildren {
  GalleryIndexRoute: typeof GalleryIndexRoute
  GalleryMemoriesIdRoute: typeof GalleryMemoriesIdRoute
  GalleryMemoriesIndexRoute: typeof GalleryMemoriesIndexRoute
}

const GalleryRouteChildren: GalleryRouteChildren = {
  GalleryIndexRoute: GalleryIndexRoute,
  GalleryMemoriesIdRoute: GalleryMemoriesIdRoute,
  GalleryMemoriesIndexRoute: GalleryMemoriesIndexRoute,
}

const GalleryRouteWithChildren =
  GalleryRoute._addFileChildren(GalleryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  GalleryRoute: GalleryRouteWithChildren,
  ImportLazyRoute: ImportLazyRoute,
  PairingLazyRoute: PairingLazyRoute,
  ScanLazyRoute: ScanLazyRoute,
  SetupLazyRoute: SetupLazyRoute,
  VaultsLazyRoute: VaultsLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
