AWSTemplateFormatVersion: '2010-09-09'
Description: 'Boreal Vault Infrastructure: S3 Bucket and IAM User'

Parameters:
  VaultName:
    Type: String
    Description: 'Name of the Vault (used for Bucket naming suffix)'
    Default: 'boreal-vault'
    AllowedPattern: '[a-z0-9-]+'
  
  StorageTier:
    Type: String
    Description: 'Storage class for original files. DEEP_ARCHIVE is cheapest but takes 12-48 hours to retrieve. GLACIER_IR is 4x more expensive but instant.'
    Default: 'DEEP_ARCHIVE'
    AllowedValues:
      - DEEP_ARCHIVE
      - GLACIER_IR

Resources:
  # S3 Bucket for Vault Storage
  VaultBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      # Append a unique suffix from the Stack ID to ensure uniqueness
      BucketName: !Sub 
        - 'boreal-${VaultName}-${AWS::AccountId}-${AWS::Region}-${StackGuid}'
        - StackGuid: !Select [0, !Split ['-', !Select [2, !Split ['/', !Ref 'AWS::StackId']]]]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          # Fresh Upload: Files tagged with fresh=true stay in Standard for 60 days
          # before transitioning to the selected storage tier
          - Id: 'ArchiveFreshOriginals'
            Prefix: 'originals/'
            Status: Enabled
            TagFilters:
              - Key: fresh
                Value: 'true'
            Transitions:
              - TransitionInDays: 60
                StorageClass: !Ref StorageTier
          # Archive Upload: Files without fresh tag (or fresh=false) transition after 1 day
          - Id: 'ArchiveOriginals'
            Prefix: 'originals/'
            Status: Enabled
            TagFilters:
              - Key: fresh
                Value: 'false'
            Transitions:
              - TransitionInDays: 1
                StorageClass: !Ref StorageTier
          # Note: thumbnails/, db/, audio/, and vault-key.enc stay in Standard (no rule needed)

  # IAM User for the App
  VaultUser:
    Type: 'AWS::IAM::User'
    Properties:
      # Append a unique suffix from the Stack ID to ensure uniqueness even if StackName is reused after deletion failure
      # StackId format: arn:aws:cloudformation:region:account:stack/stack-name/guid
      UserName: !Sub 
        - 'boreal-user-${VaultName}-${StackGuid}'
        - StackGuid: !Select [0, !Split ['-', !Select [2, !Split ['/', !Ref 'AWS::StackId']]]]
      Policies:
        - PolicyName: 'BorealBucketAccess'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # S3 bucket operations
              - Effect: Allow
                Action:
                  - 's3:PutObject'
                  - 's3:GetObject'
                  - 's3:ListBucket'
                  - 's3:DeleteObject'
                  - 's3:RestoreObject'
                  - 's3:PutObjectTagging'
                  - 's3:GetObjectTagging'
                  - 's3:DeleteBucket'
                Resource:
                  - !GetAtt VaultBucket.Arn
                  - !Sub '${VaultBucket.Arn}/*'
              # IAM key management for credential rotation (access revocation)
              - Effect: Allow
                Action:
                  - 'iam:CreateAccessKey'
                  - 'iam:DeleteAccessKey'
                  - 'iam:ListAccessKeys'
                Resource: !Sub 
                  - 'arn:aws:iam::${AWS::AccountId}:user/boreal-user-${VaultName}-${StackGuid}'
                  - StackGuid: !Select [0, !Split ['-', !Select [2, !Split ['/', !Ref 'AWS::StackId']]]]

  # Access Keys for the User
  VaultAccessKey:
    Type: 'AWS::IAM::AccessKey'
    Properties: 
      UserName: !Ref VaultUser

Outputs:
  VaultCode:
    Description: 'Copy this code into the Boreal app'
    Value: !Sub '{"bucket":"${VaultBucket}","region":"${AWS::Region}","access_key_id":"${VaultAccessKey}","secret_access_key":"${VaultAccessKey.SecretAccessKey}"}'
