import QRCode from "react-qr-code";

interface RecoveryKitProps {
  vaultName: string;
  rawCode: string;
}

// Deep link to the manual recovery page in the app
const MANUAL_RECOVERY_URL = "boreal://recover";

export function RecoveryKit({ vaultName, rawCode }: RecoveryKitProps) {
  const formattedRawCode = (() => {
    try {
      return JSON.stringify(JSON.parse(rawCode), null, 2);
    } catch {
      return rawCode;
    }
  })();

  const generatedDate = new Date().toLocaleDateString(undefined, {
    year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit'
  });

  return (
    <div className="recovery-kit-container bg-white text-black p-8 font-serif max-w-[210mm] mx-auto border border-gray-200 shadow-sm print:shadow-none print:border-none print:m-0 print:p-0 print:w-full print:max-w-none">

      {/* Print Styles */}
      <style>{`
        @media print {
          body > *:not(#print-portal-root) { display: none !important; }
          #print-portal-root { 
            display: block !important; 
            position: absolute; 
            top: 0; left: 0; 
            width: 100%; height: 100%;
            background: white;
            z-index: 9999;
          }
          #recovery-kit-root { width: 100%; height: 100%; }
          @page { margin: 0; size: auto; }
        }
      `}</style>

      <div id="recovery-kit-root" className="p-12 max-w-[210mm] mx-auto">
        <header className="mb-8 border-b-2 border-black pb-4 flex justify-between items-end">
          <div>
            <h1 className="text-3xl font-bold mb-2 uppercase tracking-wide">Recovery Kit</h1>
            <p className="text-gray-600 italic">Boreal Vault Security Document</p>
          </div>
          <p className="text-xs text-gray-400 mb-1">{generatedDate}</p>
        </header>

        <section className="mb-8 flex flex-row items-start gap-8">
          <div className="shrink-0">
            <div className="border-2 border-black p-2 inline-block">
              <QRCode
                value={MANUAL_RECOVERY_URL}
                size={150}
                level="L"
              />
            </div>
            <p className="mt-2 text-xs text-center font-mono text-gray-500">SCAN TO OPEN RECOVERY</p>
          </div>

          <div className="flex-1 pt-2">
            <h2 className="text-xl font-bold mb-1">Vault: {vaultName}</h2>
            <p className="text-sm text-gray-600 mb-4">
              This document contains the keys to access your secure vault.
              Store it in a physically secure location, such as a safe.
            </p>
            <p className="text-xs text-gray-500 italic">
              The QR code opens the recovery page where you can manually enter
              the raw recovery data below.
            </p>
          </div>
        </section>

        <section className="mb-8">
          <div className="bg-red-50 border border-red-200 p-4 rounded text-red-900 text-sm flex gap-3 items-start">
            <div className="font-bold text-lg mt-0.5">⚠️</div>
            <div>
              <strong className="block mb-1">CRITICAL WARNING</strong>
              Anyone with this document can access your files.
              Do not store this digitally. Do not take a photo of this.
              Burn or shred after use if shifting purely to digital storage.
            </div>
          </div>
        </section>

        <section>
          <h3 className="font-bold mb-2 uppercase text-sm border-b border-gray-300 pb-1">Raw Recovery Data</h3>
          <p className="text-xs text-gray-500 mb-3">
            <strong>Type this data manually</strong> into the recovery page.
            Do not copy/paste digitally or photograph this document.
          </p>
          <pre className="font-mono text-[9px] bg-gray-50 p-3 border border-gray-200 whitespace-pre-wrap break-all leading-tight text-gray-700">
            {formattedRawCode}
          </pre>
        </section>

        <footer className="mt-12 pt-4 border-t border-gray-200 text-center text-xs text-gray-400">
          Generated by Boreal Client • Keep Secure
        </footer>
      </div>
    </div>
  );
}
